import type { ResourceConfig } from '../components/ResourcePage'

const projectStatus = [
  { label: 'Borrador', value: 'draft' },
  { label: 'Cotizado', value: 'quoted' },
  { label: 'Aprobado', value: 'approved' },
  { label: 'En obra', value: 'in_execution' },
  { label: 'Pausado', value: 'paused' },
  { label: 'Terminado', value: 'completed' },
  { label: 'Cancelado', value: 'cancelled' },
]

const quoteStatus = [
  { label: 'Borrador', value: 'draft' },
  { label: 'Enviada', value: 'sent' },
  { label: 'Aprobada', value: 'approved' },
  { label: 'Rechazada', value: 'rejected' },
  { label: 'Cancelada', value: 'cancelled' },
]

const supplySourceOptions = [
  { label: 'Constructora', value: 'constructor' },
  { label: 'Desarrolladora', value: 'developer' },
  { label: 'Tercero', value: 'third_party' },
]

function relationIds(item: Record<string, unknown>, key: string) {
  const values = item[key]
  if (!Array.isArray(values)) return []
  return values
    .map((value) => {
      if (value && typeof value === 'object' && 'id' in value) {
        return String((value as { id: number }).id)
      }
      return ''
    })
    .filter(Boolean)
}

export const resources: Record<string, ResourceConfig> = {
  companies: {
    title: 'Constructoras',
    endpoint: '/companies',
    createEndpoint: '/companies/onboard',
    permissionName: 'companies',
    createModuleLabel: 'Alta de licencia con administrador inicial',
    editModuleLabel: 'Datos de licencia',
    columns: ['id', 'name', 'plan_name', 'max_users', 'license_status', 'license_expires_at'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      plan_name: 'Plan',
      max_users: 'Usuarios incluidos',
      license_status: 'Estado licencia',
      license_expires_at: 'Vence licencia',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_email', label: 'Correo contacto', type: 'email' },
      { name: 'contact_phone', label: 'Telefono contacto' },
      { name: 'plan_name', label: 'Plan', defaultValue: 'standard', required: true },
      { name: 'max_users', label: 'Usuarios incluidos', type: 'number', defaultValue: '5', required: true },
      {
        name: 'license_status',
        label: 'Estado licencia',
        type: 'select',
        defaultValue: 'active',
        required: true,
        options: ['trial', 'active', 'expired', 'suspended', 'cancelled'].map((value) => ({
          label: value,
          value,
        })),
      },
      { name: 'license_starts_at', label: 'Inicio licencia', type: 'date' },
      { name: 'license_expires_at', label: 'Vence licencia', type: 'date' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
    createFields: [
      { name: 'name', label: 'Nombre constructora', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_email', label: 'Correo contacto', type: 'email' },
      { name: 'contact_phone', label: 'Telefono contacto' },
      { name: 'plan_name', label: 'Plan', defaultValue: 'standard', required: true },
      { name: 'max_users', label: 'Usuarios incluidos', type: 'number', defaultValue: '5', required: true },
      {
        name: 'license_status',
        label: 'Estado licencia',
        type: 'select',
        defaultValue: 'active',
        required: true,
        options: ['trial', 'active', 'expired', 'suspended', 'cancelled'].map((value) => ({
          label: value,
          value,
        })),
      },
      { name: 'license_starts_at', label: 'Inicio licencia', type: 'date' },
      { name: 'license_expires_at', label: 'Vence licencia', type: 'date' },
      { name: 'admin_full_name', label: 'Nombre administrador', required: true },
      { name: 'admin_email', label: 'Correo administrador', type: 'email', required: true },
      { name: 'admin_password', label: 'Contrasena administrador', type: 'password', required: true },
      { name: 'create_default_roles', label: 'Crear roles base', type: 'checkbox', defaultValue: true },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  clients: {
    title: 'Desarrolladoras',
    endpoint: '/clients',
    permissionName: 'clients',
    columns: ['id', 'name', 'legal_name', 'contact_name', 'contact_email'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      legal_name: 'Razon social',
      contact_name: 'Contacto',
      contact_email: 'Correo',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_name', label: 'Contacto' },
      { name: 'contact_phone', label: 'Telefono' },
      { name: 'contact_email', label: 'Correo', type: 'email' },
      { name: 'address', label: 'Direccion', type: 'textarea' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  projects: {
    title: 'Desarrollos',
    endpoint: '/projects',
    permissionName: 'projects',
    columns: ['id', 'client_id', 'name', 'location', 'status'],
    columnLabels: {
      id: 'ID',
      client_id: 'Desarrolladora',
      name: 'Nombre',
      location: 'Ubicacion',
      status: 'Estado',
    },
    fields: [
      {
        name: 'client_id',
        label: 'Desarrolladora',
        type: 'number',
        required: true,
        relation: { endpoint: '/clients', labelField: 'name' },
      },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'location', label: 'Ubicacion' },
      { name: 'status', label: 'Estado', type: 'select', options: projectStatus, required: true, defaultValue: 'draft' },
      { name: 'start_date', label: 'Inicio', type: 'date' },
      { name: 'estimated_end_date', label: 'Fin estimado', type: 'date' },
    ],
  },
  houseModels: {
    title: 'Modelos por desarrolladora',
    endpoint: '/house-models',
    permissionName: 'house_models',
    columns: ['id', 'client_id', 'name', 'construction_m2', 'levels', 'bedrooms', 'bathrooms'],
    columnLabels: {
      id: 'ID',
      client_id: 'Desarrolladora',
      name: 'Nombre',
      construction_m2: 'm2 construccion',
      levels: 'Niveles',
      bedrooms: 'Recamaras',
      bathrooms: 'Banos',
    },
    fields: [
      {
        name: 'client_id',
        label: 'Desarrolladora',
        type: 'number',
        required: true,
        relation: { endpoint: '/clients', labelField: 'name' },
      },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'construction_m2', label: 'm2 construccion', type: 'number', step: '0.01', required: true },
      { name: 'levels', label: 'Niveles', type: 'number' },
      { name: 'bedrooms', label: 'Recamaras', type: 'number' },
      { name: 'bathrooms', label: 'Banos', type: 'number', step: '0.5' },
      { name: 'base_notes', label: 'Notas base', type: 'textarea' },
    ],
  },
  projectMaterialPrices: {
    title: 'Tabulador del desarrollo',
    endpoint: '/project-material-prices',
    permissionName: 'materials',
    columns: [
      'id',
      'project_id',
      'house_model_id',
      'material_id',
      'unit',
      'unit_price',
      'supply_source',
      'include_in_quote',
    ],
    columnLabels: {
      id: 'ID',
      project_id: 'Desarrollo',
      house_model_id: 'Modelo',
      material_id: 'Material',
      unit: 'Unidad',
      unit_price: 'Precio unitario',
      supply_source: 'Lo provee',
      include_in_quote: 'Cotizar',
    },
    fields: [
      {
        name: 'project_id',
        label: 'Desarrollo',
        type: 'number',
        required: true,
        relation: { endpoint: '/projects', labelField: 'name' },
      },
      {
        name: 'house_model_id',
        label: 'Modelo del desarrollo',
        type: 'number',
        relation: { endpoint: '/house-models', labelField: 'name' },
      },
      {
        name: 'material_id',
        label: 'Material',
        type: 'number',
        required: true,
        relation: { endpoint: '/materials', labelField: 'name' },
      },
      { name: 'unit', label: 'Unidad' },
      { name: 'unit_price', label: 'Precio unitario', type: 'number', step: '0.0001', required: true },
      { name: 'supply_source', label: 'Lo provee', type: 'select', options: supplySourceOptions, required: true, defaultValue: 'constructor' },
      { name: 'supplier_name', label: 'Proveedor' },
      { name: 'include_in_quote', label: 'Incluir en cotizacion', type: 'checkbox', defaultValue: true },
      { name: 'source_document_name', label: 'Documento fuente' },
      { name: 'effective_date', label: 'Fecha precio', type: 'date' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  materials: {
    title: 'Catalogo de materiales',
    endpoint: '/materials',
    permissionName: 'materials',
    columns: ['id', 'name', 'unit', 'current_unit_price', 'supplier_name', 'is_active'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      unit: 'Unidad',
      current_unit_price: 'Precio unitario',
      supplier_name: 'Proveedor',
      is_active: 'Activo',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'unit', label: 'Unidad', required: true },
      { name: 'current_unit_price', label: 'Precio unitario', type: 'number', step: '0.0001', required: true },
      { name: 'supplier_name', label: 'Proveedor' },
      { name: 'last_price_update', label: 'Fecha precio', type: 'date' },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  suppliers: {
    title: 'Proveedores',
    endpoint: '/purchasing/suppliers',
    permissionName: 'suppliers',
    columns: ['id', 'name', 'contact_name', 'contact_email', 'payment_terms_days', 'status'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      contact_name: 'Contacto',
      contact_email: 'Correo',
      payment_terms_days: 'Credito dias',
      status: 'Estado',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_name', label: 'Contacto' },
      { name: 'contact_email', label: 'Correo', type: 'email' },
      { name: 'contact_phone', label: 'Telefono' },
      { name: 'payment_terms_days', label: 'Credito dias', type: 'number', defaultValue: '30', required: true },
      { name: 'average_delivery_days', label: 'Entrega promedio dias', type: 'number' },
      { name: 'material_categories', label: 'Categorias de material' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'active',
        required: true,
        options: [
          { label: 'Activo', value: 'active' },
          { label: 'Suspendido', value: 'suspended' },
          { label: 'Bloqueado', value: 'blocked' },
        ],
      },
      { name: 'address', label: 'Direccion', type: 'textarea' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  laborRates: {
    title: 'Mano de obra',
    endpoint: '/labor-rates',
    permissionName: 'labor',
    columns: ['id', 'name', 'unit', 'unit_cost', 'performance_per_day', 'is_active'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      unit: 'Unidad',
      unit_cost: 'Costo unitario',
      performance_per_day: 'Rendimiento por dia',
      is_active: 'Activo',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'unit', label: 'Unidad', required: true },
      { name: 'unit_cost', label: 'Costo unitario', type: 'number', step: '0.0001', required: true },
      { name: 'performance_per_day', label: 'Rendimiento por dia', type: 'number', step: '0.0001' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  constructionConcepts: {
    title: 'Conceptos de obra',
    endpoint: '/construction-concepts',
    permissionName: 'construction_concepts',
    columns: ['id', 'code', 'name', 'unit', 'default_waste_percent', 'default_indirect_percent'],
    columnLabels: {
      id: 'ID',
      code: 'Codigo',
      name: 'Nombre',
      unit: 'Unidad',
      default_waste_percent: 'Desperdicio',
      default_indirect_percent: 'Indirecto',
    },
    fields: [
      { name: 'code', label: 'Codigo', required: true },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'unit', label: 'Unidad', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'default_waste_percent', label: 'Desperdicio', type: 'number', step: '0.0001' },
      { name: 'default_indirect_percent', label: 'Indirecto', type: 'number', step: '0.0001' },
    ],
  },
  quotes: {
    title: 'Cotizaciones',
    endpoint: '/quotes',
    permissionName: 'quotes',
    columns: ['id', 'project_id', 'quote_number', 'version', 'status', 'total_price'],
    columnLabels: {
      id: 'ID',
      project_id: 'Desarrollo',
      quote_number: 'Numero',
      version: 'Version',
      status: 'Estado',
      total_price: 'Total',
    },
    fields: [
      {
        name: 'project_id',
        label: 'Desarrollo',
        type: 'number',
        required: true,
        relation: { endpoint: '/projects', labelField: 'name' },
      },
      { name: 'quote_number', label: 'Numero' },
      { name: 'version', label: 'Version', type: 'number', required: true, defaultValue: '1' },
      { name: 'status', label: 'Estado', type: 'select', options: quoteStatus, required: true, defaultValue: 'draft' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
      { name: 'valid_until', label: 'Valida hasta', type: 'date' },
    ],
  },
  users: {
    title: 'Usuarios',
    endpoint: '/users',
    permissionName: 'users',
    columns: ['id', 'full_name', 'email', 'is_active', 'is_master_admin'],
    columnLabels: {
      id: 'ID',
      full_name: 'Nombre completo',
      email: 'Correo',
      is_active: 'Activo',
      is_master_admin: 'Admin maestro',
    },
    fields: [
      { name: 'full_name', label: 'Nombre completo', required: true },
      {
        name: 'company_id',
        label: 'Constructora',
        type: 'number',
        relation: { endpoint: '/companies', labelField: 'name' },
      },
      { name: 'email', label: 'Correo', type: 'email', required: true },
      { name: 'password', label: 'Contrasena', type: 'password' },
      {
        name: 'role_ids',
        label: 'Roles asignados',
        type: 'multiselect',
        valueType: 'number',
        relation: {
          endpoint: '/roles',
          labelField: 'name',
          formatLabel: (item) =>
            `${String(item.name ?? '')}${item.is_system_role ? ' (sistema)' : ''}`,
        },
        valueFromItem: (item) => relationIds(item, 'roles'),
      },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
      { name: 'is_master_admin', label: 'Administrador maestro', type: 'checkbox' },
    ],
  },
  roles: {
    title: 'Roles',
    endpoint: '/roles',
    permissionName: 'roles',
    columns: ['id', 'company_id', 'name', 'description', 'is_system_role'],
    columnLabels: {
      id: 'ID',
      company_id: 'Constructora',
      name: 'Nombre',
      description: 'Descripcion',
      is_system_role: 'Rol de sistema',
    },
    fields: [
      {
        name: 'company_id',
        label: 'Constructora',
        type: 'number',
        relation: { endpoint: '/companies', labelField: 'name' },
      },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      {
        name: 'permission_ids',
        label: 'Permisos',
        type: 'permission-checklist',
        valueType: 'number',
        relation: {
          endpoint: '/permissions',
          labelField: 'description',
          formatLabel: (item) =>
            `${String(item.description ?? '')} (${String(item.module ?? '')}:${String(item.action ?? '')})`,
        },
        valueFromItem: (item) => relationIds(item, 'permissions'),
      },
      { name: 'is_system_role', label: 'Rol de sistema', type: 'checkbox' },
    ],
  },
}
