import type { ResourceConfig } from '../components/ResourcePage'

const projectStatus = [
  { label: 'Borrador', value: 'draft' },
  { label: 'Cotizado', value: 'quoted' },
  { label: 'Aprobado', value: 'approved' },
  { label: 'En obra', value: 'in_execution' },
  { label: 'Pausado', value: 'paused' },
  { label: 'Terminado', value: 'completed' },
  { label: 'Cancelado', value: 'cancelled' },
]

function relationIds(item: Record<string, unknown>, key: string) {
  const values = item[key]
  if (!Array.isArray(values)) return []
  return values
    .map((value) => {
      if (value && typeof value === 'object' && 'id' in value) {
        return String((value as { id: number }).id)
      }
      return ''
    })
    .filter(Boolean)
}

export const resources: Record<string, ResourceConfig> = {
  companies: {
    title: 'Constructoras',
    endpoint: '/companies',
    createEndpoint: '/companies/onboard',
    permissionName: 'companies',
    createLabel: 'Nueva constructora',
    editLabel: 'Editar constructora',
    createdMessage: 'Constructora creada correctamente',
    updatedMessage: 'Constructora actualizada correctamente',
    createModuleLabel: 'Alta de licencia con administrador inicial',
    editModuleLabel: 'Datos de licencia',
    columns: ['id', 'name', 'plan_name', 'max_users', 'license_status', 'license_expires_at'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      plan_name: 'Plan',
      max_users: 'Usuarios incluidos',
      license_status: 'Estado licencia',
      license_expires_at: 'Vence licencia',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_email', label: 'Correo contacto', type: 'email' },
      { name: 'contact_phone', label: 'Telefono contacto' },
      { name: 'plan_name', label: 'Plan', defaultValue: 'standard', required: true },
      { name: 'max_users', label: 'Usuarios incluidos', type: 'number', defaultValue: '5', required: true },
      {
        name: 'license_status',
        label: 'Estado licencia',
        type: 'select',
        defaultValue: 'active',
        required: true,
        options: ['trial', 'active', 'expired', 'suspended', 'cancelled'].map((value) => ({
          label: value,
          value,
        })),
      },
      { name: 'license_starts_at', label: 'Inicio licencia', type: 'date' },
      { name: 'license_expires_at', label: 'Vence licencia', type: 'date' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
    createFields: [
      { name: 'name', label: 'Nombre constructora', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_email', label: 'Correo contacto', type: 'email' },
      { name: 'contact_phone', label: 'Telefono contacto' },
      { name: 'plan_name', label: 'Plan', defaultValue: 'standard', required: true },
      { name: 'max_users', label: 'Usuarios incluidos', type: 'number', defaultValue: '5', required: true },
      {
        name: 'license_status',
        label: 'Estado licencia',
        type: 'select',
        defaultValue: 'active',
        required: true,
        options: ['trial', 'active', 'expired', 'suspended', 'cancelled'].map((value) => ({
          label: value,
          value,
        })),
      },
      { name: 'license_starts_at', label: 'Inicio licencia', type: 'date' },
      { name: 'license_expires_at', label: 'Vence licencia', type: 'date' },
      { name: 'admin_full_name', label: 'Nombre administrador', required: true },
      { name: 'admin_email', label: 'Correo administrador', type: 'email', required: true },
      { name: 'admin_password', label: 'Contrasena administrador', type: 'password', required: true },
      { name: 'create_default_roles', label: 'Crear roles base', type: 'checkbox', defaultValue: true },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  clients: {
    title: 'Inmobiliarias',
    endpoint: '/clients',
    permissionName: 'clients',
    createLabel: 'Nueva inmobiliaria',
    editLabel: 'Editar inmobiliaria',
    createdMessage: 'Inmobiliaria creada correctamente',
    updatedMessage: 'Inmobiliaria actualizada correctamente',
    columns: ['id', 'name', 'legal_name', 'contact_name', 'contact_email'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      legal_name: 'Razon social',
      contact_name: 'Contacto',
      contact_email: 'Correo',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_name', label: 'Contacto' },
      { name: 'contact_phone', label: 'Telefono' },
      { name: 'contact_email', label: 'Correo', type: 'email' },
      { name: 'address', label: 'Direccion', type: 'textarea' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  projects: {
    title: 'Desarrollos',
    endpoint: '/projects',
    permissionName: 'projects',
    columns: ['id', 'client_id', 'name', 'location', 'status'],
    columnLabels: {
      id: 'ID',
      client_id: 'Inmobiliaria',
      name: 'Nombre',
      location: 'Ubicacion',
      status: 'Estado',
    },
    fields: [
      {
        name: 'client_id',
        label: 'Inmobiliaria',
        type: 'number',
        required: true,
        relation: { endpoint: '/clients', labelField: 'name' },
      },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'location', label: 'Ubicacion' },
      { name: 'status', label: 'Estado', type: 'select', options: projectStatus, required: true, defaultValue: 'draft' },
      { name: 'start_date', label: 'Inicio', type: 'date' },
      { name: 'estimated_end_date', label: 'Fin estimado', type: 'date' },
    ],
  },
  houseModels: {
    title: 'Modelos por inmobiliaria',
    endpoint: '/house-models',
    permissionName: 'house_models',
    columns: ['id', 'client_id', 'name', 'construction_m2', 'levels', 'bedrooms', 'bathrooms'],
    columnLabels: {
      id: 'ID',
      client_id: 'Inmobiliaria',
      name: 'Nombre',
      construction_m2: 'm2 construccion',
      levels: 'Niveles',
      bedrooms: 'Recamaras',
      bathrooms: 'Banos',
    },
    fields: [
      {
        name: 'client_id',
        label: 'Inmobiliaria',
        type: 'number',
        required: true,
        relation: { endpoint: '/clients', labelField: 'name' },
      },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'construction_m2', label: 'm2 construccion', type: 'number', step: '0.01', required: true },
      { name: 'levels', label: 'Niveles', type: 'number' },
      { name: 'bedrooms', label: 'Recamaras', type: 'number' },
      { name: 'bathrooms', label: 'Banos', type: 'number', step: '0.5' },
      { name: 'base_notes', label: 'Notas base', type: 'textarea' },
    ],
  },
  materials: {
    title: 'Catalogo de materiales',
    endpoint: '/materials',
    permissionName: 'materials',
    createLabel: 'Nuevo material',
    editLabel: 'Editar material',
    createdMessage: 'Material guardado correctamente',
    updatedMessage: 'Material actualizado correctamente',
    columns: ['id', 'name', 'unit', 'current_unit_price', 'supplier_name', 'is_active'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      unit: 'Unidad',
      current_unit_price: 'Precio unitario',
      supplier_name: 'Proveedor',
      is_active: 'Activo',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'unit', label: 'Unidad', required: true },
      { name: 'current_unit_price', label: 'Precio unitario', type: 'number', step: '0.0001', required: true },
      { name: 'supplier_name', label: 'Proveedor' },
      { name: 'last_price_update', label: 'Fecha precio', type: 'date' },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  suppliers: {
    title: 'Proveedores',
    endpoint: '/purchasing/suppliers',
    permissionName: 'suppliers',
    createLabel: 'Nuevo proveedor',
    editLabel: 'Editar proveedor',
    createdMessage: 'Proveedor guardado correctamente',
    updatedMessage: 'Proveedor actualizado correctamente',
    columns: ['id', 'name', 'contact_name', 'contact_email', 'payment_terms_days', 'status'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      contact_name: 'Contacto',
      contact_email: 'Correo',
      payment_terms_days: 'Credito dias',
      status: 'Estado',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'legal_name', label: 'Razon social' },
      { name: 'tax_id', label: 'RFC' },
      { name: 'contact_name', label: 'Contacto' },
      { name: 'contact_email', label: 'Correo', type: 'email' },
      { name: 'contact_phone', label: 'Telefono' },
      { name: 'payment_terms_days', label: 'Credito dias', type: 'number', defaultValue: '30', required: true },
      { name: 'average_delivery_days', label: 'Entrega promedio dias', type: 'number' },
      { name: 'material_categories', label: 'Categorias de material' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'active',
        required: true,
        options: [
          { label: 'Activo', value: 'active' },
          { label: 'Suspendido', value: 'suspended' },
          { label: 'Bloqueado', value: 'blocked' },
        ],
      },
      { name: 'address', label: 'Direccion', type: 'textarea' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  laborRates: {
    title: 'Mano de obra',
    endpoint: '/labor-rates',
    permissionName: 'labor',
    createLabel: 'Nueva mano de obra',
    editLabel: 'Editar mano de obra',
    createdMessage: 'Mano de obra guardada correctamente',
    updatedMessage: 'Mano de obra actualizada correctamente',
    columns: ['id', 'name', 'unit', 'unit_cost', 'performance_per_day', 'is_active'],
    columnLabels: {
      id: 'ID',
      name: 'Nombre',
      unit: 'Unidad',
      unit_cost: 'Costo unitario',
      performance_per_day: 'Rendimiento por dia',
      is_active: 'Activo',
    },
    fields: [
      { name: 'name', label: 'Nombre', required: true },
      { name: 'unit', label: 'Unidad', required: true },
      { name: 'unit_cost', label: 'Costo unitario', type: 'number', step: '0.0001', required: true },
      { name: 'performance_per_day', label: 'Rendimiento por dia', type: 'number', step: '0.0001' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  constructionConcepts: {
    title: 'Conceptos de obra',
    endpoint: '/construction-concepts',
    permissionName: 'construction_concepts',
    createLabel: 'Nuevo concepto',
    editLabel: 'Editar concepto',
    createdMessage: 'Concepto guardado correctamente',
    updatedMessage: 'Concepto actualizado correctamente',
    columns: ['id', 'code', 'name', 'unit', 'default_waste_percent', 'default_indirect_percent'],
    columnLabels: {
      id: 'ID',
      code: 'Codigo',
      name: 'Nombre',
      unit: 'Unidad',
      default_waste_percent: 'Desperdicio',
      default_indirect_percent: 'Indirecto',
    },
    fields: [
      { name: 'code', label: 'Codigo', required: true },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'unit', label: 'Unidad', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      { name: 'default_waste_percent', label: 'Desperdicio', type: 'number', step: '0.0001' },
      { name: 'default_indirect_percent', label: 'Indirecto', type: 'number', step: '0.0001' },
    ],
  },
  users: {
    title: 'Usuarios',
    endpoint: '/users',
    permissionName: 'users',
    createLabel: 'Nuevo usuario',
    editLabel: 'Editar usuario',
    createdMessage: 'Usuario guardado correctamente',
    updatedMessage: 'Usuario actualizado correctamente',
    columns: ['id', 'full_name', 'email', 'client_access_mode', 'is_active', 'is_master_admin'],
    columnLabels: {
      id: 'ID',
      full_name: 'Nombre completo',
      email: 'Correo',
      client_access_mode: 'Alcance inmobiliarias',
      is_active: 'Activo',
      is_master_admin: 'Admin maestro',
    },
    fields: [
      { name: 'full_name', label: 'Nombre completo', required: true },
      {
        name: 'company_id',
        label: 'Constructora',
        type: 'number',
        relation: { endpoint: '/companies', labelField: 'name' },
      },
      { name: 'email', label: 'Correo', type: 'email', required: true },
      { name: 'password', label: 'Contrasena', type: 'password' },
      {
        name: 'role_ids',
        label: 'Roles asignados',
        type: 'multiselect',
        valueType: 'number',
        relation: {
          endpoint: '/roles',
          labelField: 'name',
          formatLabel: (item) =>
            `${String(item.name ?? '')}${item.is_system_role ? ' (sistema)' : ''}`,
        },
        valueFromItem: (item) => relationIds(item, 'roles'),
      },
      {
        name: 'client_access_mode',
        label: 'Acceso a inmobiliarias',
        type: 'select',
        defaultValue: 'all',
        options: [
          { label: 'Todas las inmobiliarias', value: 'all' },
          { label: 'Solo inmobiliarias seleccionadas', value: 'restricted' },
        ],
      },
      {
        name: 'client_ids',
        label: 'Inmobiliarias permitidas',
        type: 'multiselect',
        valueType: 'number',
        relation: { endpoint: '/clients', labelField: 'name' },
        valueFromItem: (item) => relationIds(item, 'clients'),
      },
      { name: 'is_active', label: 'Activo', type: 'checkbox', defaultValue: true },
      { name: 'is_master_admin', label: 'Administrador maestro', type: 'checkbox' },
    ],
  },
  roles: {
    title: 'Roles',
    endpoint: '/roles',
    permissionName: 'roles',
    createLabel: 'Nuevo rol',
    editLabel: 'Editar rol',
    createdMessage: 'Rol guardado correctamente',
    updatedMessage: 'Rol actualizado correctamente',
    columns: ['id', 'company_id', 'name', 'description', 'is_system_role'],
    columnLabels: {
      id: 'ID',
      company_id: 'Constructora',
      name: 'Nombre',
      description: 'Descripcion',
      is_system_role: 'Rol de sistema',
    },
    fields: [
      {
        name: 'company_id',
        label: 'Constructora',
        type: 'number',
        relation: { endpoint: '/companies', labelField: 'name' },
      },
      { name: 'name', label: 'Nombre', required: true },
      { name: 'description', label: 'Descripcion', type: 'textarea' },
      {
        name: 'permission_ids',
        label: 'Permisos',
        type: 'permission-checklist',
        valueType: 'number',
        relation: {
          endpoint: '/permissions',
          labelField: 'description',
          formatLabel: (item) =>
            `${String(item.description ?? '')} (${String(item.module ?? '')}:${String(item.action ?? '')})`,
        },
        valueFromItem: (item) => relationIds(item, 'permissions'),
      },
      { name: 'is_system_role', label: 'Rol de sistema', type: 'checkbox' },
    ],
  },
}
